import React, { createContext, useContext, useState, useEffect } from 'react';

// Define the supported languages
export type Language = 'en' | 'de' | 'es';

// Language context type
interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.bots': 'Bots',
    'nav.add-bot': 'Add Bot',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.login': 'Log In',
    'nav.register': 'Register',
    'nav.logout': 'Log Out',
    'nav.search': 'Search',
    'nav.servers': 'Servers',
    'nav.add-server': 'Add Server',
    'nav.account': 'Account',
    
    // Home page
    'home.title': 'Discover Discord Bots',
    'home.subtitle': 'Find the perfect bot for your Discord server',
    'home.search-placeholder': 'Search by name, category, or feature',
    'home.explore': 'Explore Bots',
    'home.popular': 'Popular Bots',
    'home.recent': 'Recently Added',
    'home.featured': 'Featured Bots',
    
    // Auth
    'auth.login': 'Log In',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm-password': 'Confirm Password',
    'auth.username': 'Username',
    'auth.username-placeholder': 'Enter your username',
    'auth.forgot-password': 'Forgot Password?',
    'auth.already-account': 'Already have an account?',
    'auth.no-account': 'Don\'t have an account?',
    'auth.or': 'or',
    'auth.login-with-google': 'Log in with Google',
    'auth.register-with-google': 'Register with Google',
    'auth.login-with-discord': 'Log in with Discord',
    'auth.register-with-discord': 'Register with Discord',
    'auth.login-description': 'Sign in to your account to manage your bots and servers',
    'auth.register-description': 'Create an account to add your bots and servers to our directory',
    
    // Bot details
    'bot.add': 'Add Bot',
    'bot.edit': 'Edit Bot',
    'bot.delete': 'Delete Bot',
    'bot.name': 'Bot Name',
    'bot.description': 'Description',
    'bot.id': 'Bot ID',
    'bot.prefix': 'Prefix',
    'bot.category': 'Category',
    'bot.website': 'Website',
    'bot.invite': 'Invite Bot',
    'bot.support': 'Support Server',
    'bot.github': 'GitHub Repository',
    'bot.tags': 'Tags',
    'bot.save': 'Save Bot',
    'bot.cancel': 'Cancel',
    'bot.owner': 'Owner',
    'bot.created': 'Created',
    'bot.updated': 'Updated',
    'bot.stars': 'stars',
    'bot.verified': 'Verified',
    'bot.no-description': 'No description provided',
    'bot.unknown': 'Unknown',
    'bot.not-found': 'Bot Not Found',
    'bot.not-found-description': 'The bot you\'re looking for doesn\'t exist or has been removed.',
    'bot.back-to-bots': 'Back to Bots',
    'bot.view-details': 'View Details',
    'bot.directory': 'Bot Directory',
    'bot.directory-desc': 'Browse and discover Discord bots for your server',
    'bot.none-found': 'No bots found',
    'bot.be-first': 'Be the first to add a bot!',
    'bot.add-yours': 'Add Your Bot',
    'bot.last-updated': 'Last Updated',
    'bot.bump': 'Bump',
    'bot.bumping': 'Bumping...',
    
    // Server
    'server.add': 'Add Server',
    'server.edit': 'Edit Server',
    'server.delete': 'Delete Server',
    'server.name': 'Server Name',
    'server.description': 'Description',
    'server.invite': 'Invite Link',
    'server.members': 'Members',
    'server.join': 'Join Server',
    'server.tags': 'Tags',
    
    // Admin
    'admin.title': 'Admin Panel',
    'admin.users': 'Users',
    'admin.bots': 'Bots',
    'admin.reports': 'Reports',
    'admin.settings': 'Settings',
    'admin.pending': 'Pending Bots',
    'admin.servers': 'Discord Servers',
    'admin.overview': 'Overview',
    'admin.user-management': 'User Management',
    'admin.manage-users-permissions': 'Manage users and their permissions',
    'admin.verified-bots': 'Verified Bots',
    'admin.pending-bots': 'Pending Verification',
    'admin.server-management': 'Server Management',
    'admin.total-users': 'Total Users',
    'admin.total-bots': 'Total Bots',
    'admin.total-servers': 'Total Servers',
    'admin.pending-verification': 'Pending Verification',
    'admin.registered-users': 'Registered Users',
    'admin.verification-required': 'Verification Required',
    'admin.refresh': 'Refresh',
    'admin.approve': 'Approve',
    'admin.decline': 'Decline',
    'admin.remove-admin': 'Remove Admin Rights',
    'admin.make-admin': 'Make Admin',
    'admin.last-updated': 'Last Updated',
    'admin.user-details': 'User Details',
    'admin.close': 'Close',
    'admin.error-fetching-bots': 'Error fetching bots',
    'admin.error-fetching-users': 'Error fetching users',
    'admin.error-fetching-servers': 'Error fetching servers',
    'admin.error-updating-admin-status': 'Error updating admin status',
    'admin.error-verifying-bot': 'Error verifying bot',
    'admin.error-deleting-bot': 'Error deleting bot',
    'admin.error-deleting-server': 'Error deleting server',
    'admin.admin-status-updated': 'Admin status updated',
    'admin.user-is-now-admin': 'User is now an admin',
    'admin.user-no-longer-admin': 'User is no longer an admin',
    'admin.bot-verified': 'Bot verified',
    'admin.bot-verified-success': 'Bot has been verified successfully',
    'admin.bot-deleted': 'Bot deleted',
    'admin.bot-deleted-success': 'Bot has been deleted successfully',
    'admin.server-deleted': 'Server deleted',
    'admin.server-deleted-success': 'Server has been deleted successfully',
    'admin.confirm-delete-bot': 'Are you sure you want to delete this bot?',
    'admin.confirm-delete-server': 'Are you sure you want to delete this server?',
    'admin.access-denied': 'Access denied',
    'admin.no-admin-rights': 'You do not have admin rights',
    'admin.actions': 'Actions',
    'admin.joined': 'Joined',
    'admin.added': 'Added',
    'admin.no-users-found': 'No users found',
    'admin.no-bots-found': 'No bots found',
    'admin.no-pending-bots': 'No pending bots',
    'admin.no-servers-found': 'No servers found',
    'admin.user-detailed-info': 'Detailed information about the user',
    'admin.registered': 'Registered',
    'admin.last-updated': 'Last Updated',
    'admin.admin-status': 'Admin Status',
    'admin.administrator': 'Administrator',
    'admin.regular-user': 'Regular User',
    'admin.bot-management': 'Bot Management',
    'admin.bot-review': 'Review and approve pending bots',
    
    // Account manager
    'account.title': 'Account Manager',
    'account.profile': 'Profile',
    'account.settings': 'Settings',
    'account.security': 'Security',
    'account.connected': 'Connected Accounts',
    'account.theme': 'Theme',
    'account.theme.light': 'Light Mode',
    'account.theme.dark': 'Dark Mode',
    'account.theme.system': 'System Default',
    'account.language': 'Language',
    'account.save': 'Save Changes',
    'account.delete': 'Delete Account',
    
    // Footer
    'footer.privacy': 'Privacy Policy',
    'footer.imprint': 'Imprint',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact',
    'footer.language': 'Language',
    'footer.rights': 'All rights reserved',
    
    // Misc
    'misc.loading': 'Loading...',
    'misc.error': 'An error occurred',
    'misc.success': 'Success!',
    'misc.search': 'Search',
    'misc.save': 'Save',
    'misc.cancel': 'Cancel',
    'misc.delete': 'Delete',
    'misc.edit': 'Edit',
    'misc.view': 'View',
    'misc.create': 'Create',
    'misc.submit': 'Submit',
    'misc.back': 'Back',
    'misc.next': 'Next',
    'misc.previous': 'Previous',
    'misc.unknown': 'Unknown',
    'misc.back-to-bots': 'Back to Bots',
    'misc.saving': 'Saving...',
    
    // Cookie banner
    'cookie.title': 'Cookie Notice',
    'cookie.description': 'We use cookies to ensure you get the best experience on our website.',
    'cookie.accept': 'Accept All',
    'cookie.decline': 'Decline',
    'cookie.preferences': 'Customize',
    'cookie.save_preferences': 'Save Preferences',
    'cookie.customize_notice': 'You can customize your cookie preferences at any time.',
    'cookie.necessary': 'Necessary Cookies',
    'cookie.necessary_description': 'These cookies are essential for the website to function properly.',
    'cookie.analytics': 'Analytics Cookies',
    'cookie.analytics_description': 'These cookies help us understand how visitors interact with the website.',
    'cookie.preferences': 'Preferences Cookies',
    'cookie.preferences_description': 'These cookies allow the website to remember choices you make.',
    'cookie.marketing': 'Marketing Cookies',
    'cookie.marketing_description': 'These cookies are used to track visitors across websites.',
    
    // Profile
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.bots': 'My Bots',
    'profile.settings': 'Settings',
    'profile.your-profile': 'Your Profile',
    'profile.manage-details': 'Manage your profile details',
    'profile.edit-profile': 'Edit Profile',
    'profile.update-information': 'Update your profile information',
    'profile.username': 'Username',
    'profile.username-placeholder': 'Enter your username',
    'profile.bio': 'Bio',
    'profile.bio-placeholder': 'Tell us about yourself',
    'profile.website': 'Website',
    'profile.website-placeholder': 'Your website URL',
    'profile.save-changes': 'Save Changes',
    'profile.your-bots': 'Your Bots',
    'profile.manage-bots': 'Manage your Discord bots',
    'profile.view-bot': 'View Bot',
    
    // Legal
    'legal.imprint': 'Imprint',
    'legal.company-information': 'Company Information',
    'legal.company-name': 'Discord Bot Directory',
    'legal.company-address': '123 Bot Street',
    'legal.company-city': 'Bot City, 10115',
    'legal.company-country': 'Botland',
    'legal.contact': 'Contact',
    'legal.email': 'Email',
    'legal.phone': 'Phone',
    'legal.registration': 'Registration',
    'legal.registration-text': 'Registered in the Commercial Register of Bot City. Registration Number: BOT123456',
    'legal.vat': 'VAT',
    'legal.vat-text': 'VAT Identification Number according to § 27a of the Value Added Tax Act: DE123456789',
    'legal.responsible-content': 'Responsible for Content',
    'legal.responsible-content-text': 'Person responsible for content in accordance with § 55 Abs. 2 RStV: John Doe, 123 Bot Street, Bot City, 10115 Botland',
    'legal.dispute-resolution': 'Dispute Resolution',
    'legal.dispute-resolution-text': 'The European Commission provides a platform for online dispute resolution (OS): https://ec.europa.eu/consumers/odr. We are not willing or obliged to participate in dispute resolution proceedings before a consumer arbitration board.',
    'legal.privacy-policy': 'Privacy Policy',
    'legal.information-collection': 'Information Collection',
    'legal.information-collection-text': 'We collect information you provide directly to us when registering for an account, adding bots, or interacting with our platform. This includes email addresses, usernames, and Discord IDs.',
    'legal.information-usage': 'Information Usage',
    'legal.information-usage-text': 'We use information about you to provide, maintain, and improve our services, develop new features, and protect the platform and our users.',
    'legal.information-protection': 'Information Protection',
    'legal.information-protection-text': 'We implement measures designed to ensure the security of your personal information. However, no method of transmission over the Internet is 100% secure.',
    'legal.cookie-usage': 'Cookie Usage',
    'legal.cookie-usage-text': 'We use cookies and similar technologies to collect information about how you interact with our services and to remember certain preferences.',
    'legal.third-party-disclosure': 'Third-Party Disclosure',
    'legal.third-party-disclosure-text': 'We do not sell, trade, or otherwise transfer your personally identifiable information to outside parties without your consent.',
    'legal.third-party-links': 'Third-Party Links',
    'legal.third-party-links-text': 'Our service may contain links to third-party websites or services. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services.',
    'legal.gdpr-compliance': 'GDPR Compliance',
    'legal.gdpr-compliance-text': 'For users in the European Union, we provide rights regarding your personal data, including the right to access, correct, or delete your personal information.',
    'legal.childrens-privacy': 'Children\'s Privacy',
    'legal.childrens-privacy-text': 'Our services are not directed to anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13.',
    'legal.changes-to-policy': 'Changes to Policy',
    'legal.changes-to-policy-text': 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.',
    'legal.contact-us': 'Contact Us',
    'legal.contact-us-text': 'If you have any questions about this Privacy Policy, please contact us through the platform or via the provided contact information.',
    'legal.terms-of-service': 'Terms of Service',
    'legal.acceptance': 'Acceptance of Terms',
    'legal.terms-acceptance-text': 'By accessing and using this Discord Bot Directory, you accept and agree to be bound by the terms and provisions of this agreement.',
    'legal.eligibility': 'Eligibility',
    'legal.eligibility-text': 'To use our services, you must be at least 13 years of age and comply with Discord\'s Terms of Service.',
    'legal.user-accounts': 'User Accounts',
    'legal.user-accounts-text': 'Users are responsible for maintaining the security of their account and password. The platform cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.',
    'legal.user-content': 'User Content',
    'legal.user-content-text': 'You are responsible for all content and activity that occurs under your account. Harmful or abusive content is strictly prohibited.',
    'legal.prohibited-conduct': 'Prohibited Conduct',
    'legal.prohibited-conduct-text': 'Users may not engage in any activity that interferes with or disrupts the services or servers connected to the platform.',
    'legal.intellectual-property': 'Intellectual Property',
    'legal.intellectual-property-text': 'The service and its original content, features, and functionality are owned by the platform and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.',
    'legal.termination': 'Termination',
    'legal.termination-text': 'We may terminate or suspend your account and bar access to the service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation.',
    'legal.disclaimer': 'Disclaimer',
    'legal.disclaimer-text': 'Your use of the service is at your sole risk. The service is provided on an "AS IS" and "AS AVAILABLE" basis without any warranty of any kind.',
    'legal.limitation-liability': 'Limitation of Liability',
    'legal.limitation-liability-text': 'In no event shall the platform, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages.',
    'legal.governing-law': 'Governing Law',
    'legal.governing-law-text': 'These Terms shall be governed and construed in accordance with the laws applicable in the jurisdiction where the platform is registered.',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.bots': 'Bots',
    'nav.add-bot': 'Bot hinzufügen',
    'nav.admin': 'Admin',
    'nav.profile': 'Profil',
    'nav.login': 'Anmelden',
    'nav.register': 'Registrieren',
    'nav.logout': 'Abmelden',
    'nav.search': 'Suchen',
    'nav.servers': 'Server',
    'nav.add-server': 'Server hinzufügen',
    'nav.account': 'Konto',
    
    // Home page
    'home.title': 'Entdecke Discord Bots',
    'home.subtitle': 'Finde den perfekten Bot für deinen Discord-Server',
    'home.search-placeholder': 'Suche nach Name, Kategorie oder Funktion',
    'home.explore': 'Bots erkunden',
    'home.popular': 'Beliebte Bots',
    'home.recent': 'Kürzlich hinzugefügt',
    'home.featured': 'Empfohlene Bots',
    
    // Auth
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirm-password': 'Passwort bestätigen',
    'auth.username': 'Benutzername',
    'auth.username-placeholder': 'Gib deinen Benutzernamen ein',
    'auth.forgot-password': 'Passwort vergessen?',
    'auth.already-account': 'Bereits ein Konto?',
    'auth.no-account': 'Noch kein Konto?',
    'auth.or': 'oder',
    'auth.login-with-google': 'Mit Google anmelden',
    'auth.register-with-google': 'Mit Google registrieren',
    'auth.login-with-discord': 'Mit Discord anmelden',
    'auth.register-with-discord': 'Mit Discord registrieren',
    'auth.login-description': 'Melde dich an, um deine Bots und Server zu verwalten',
    'auth.register-description': 'Erstelle ein Konto, um deine Bots und Server zu unserem Verzeichnis hinzuzufügen',
    
    // Bot details
    'bot.add': 'Bot hinzufügen',
    'bot.edit': 'Bot bearbeiten',
    'bot.delete': 'Bot löschen',
    'bot.name': 'Bot-Name',
    'bot.description': 'Beschreibung',
    'bot.id': 'Bot-ID',
    'bot.prefix': 'Präfix',
    'bot.category': 'Kategorie',
    'bot.website': 'Webseite',
    'bot.invite': 'Bot einladen',
    'bot.support': 'Support-Server',
    'bot.github': 'GitHub-Repository',
    'bot.tags': 'Tags',
    'bot.save': 'Bot speichern',
    'bot.cancel': 'Abbrechen',
    'bot.owner': 'Besitzer',
    'bot.created': 'Erstellt',
    'bot.updated': 'Aktualisiert',
    'bot.stars': 'Sterne',
    'bot.verified': 'Verifiziert',
    'bot.no-description': 'Keine Beschreibung vorhanden',
    'bot.unknown': 'Unbekannt',
    'bot.not-found': 'Bot nicht gefunden',
    'bot.not-found-description': 'Der gesuchte Bot existiert nicht oder wurde entfernt.',
    'bot.back-to-bots': 'Zurück zu Bots',
    'bot.view-details': 'Details anzeigen',
    'bot.directory': 'Bot-Verzeichnis',
    'bot.directory-desc': 'Durchsuche und entdecke Discord-Bots für deinen Server',
    'bot.none-found': 'Keine Bots gefunden',
    'bot.be-first': 'Sei der Erste, der einen Bot hinzufügt!',
    'bot.add-yours': 'Füge deinen Bot hinzu',
    'bot.last-updated': 'Zuletzt aktualisiert',
    'bot.bump': 'Hochstufen',
    'bot.bumping': 'Wird hochgestuft...',
    
    // Server
    'server.add': 'Server hinzufügen',
    'server.edit': 'Server bearbeiten',
    'server.delete': 'Server löschen',
    'server.name': 'Server-Name',
    'server.description': 'Beschreibung',
    'server.invite': 'Einladungslink',
    'server.members': 'Mitglieder',
    'server.join': 'Server beitreten',
    'server.tags': 'Tags',
    
    // Admin
    'admin.title': 'Admin-Panel',
    'admin.users': 'Benutzer',
    'admin.bots': 'Bots',
    'admin.reports': 'Berichte',
    'admin.settings': 'Einstellungen',
    'admin.pending': 'Ausstehende Bots',
    'admin.servers': 'Discord-Server',
    'admin.overview': 'Übersicht',
    'admin.user-management': 'Benutzerverwaltung',
    'admin.manage-users-permissions': 'Benutzer und ihre Berechtigungen verwalten',
    'admin.verified-bots': 'Verifizierte Bots',
    'admin.pending-bots': 'Ausstehende Verifizierung',
    'admin.server-management': 'Serververwaltung',
    'admin.total-users': 'Benutzer insgesamt',
    'admin.total-bots': 'Bots insgesamt',
    'admin.total-servers': 'Server insgesamt',
    'admin.pending-verification': 'Ausstehende Verifizierung',
    'admin.registered-users': 'Registrierte Benutzer',
    'admin.verification-required': 'Prüfung erforderlich',
    'admin.refresh': 'Aktualisieren',
    'admin.approve': 'Genehmigen',
    'admin.decline': 'Ablehnen',
    'admin.remove-admin': 'Admin-Rechte entfernen',
    'admin.make-admin': 'Zum Admin machen',
    'admin.last-updated': 'Zuletzt aktualisiert',
    'admin.user-details': 'Benutzerdetails',
    'admin.close': 'Schließen',
    'admin.error-fetching-bots': 'Fehler beim Abrufen der Bots',
    'admin.error-fetching-users': 'Fehler beim Abrufen der Benutzer',
    'admin.error-fetching-servers': 'Fehler beim Abrufen der Server',
    'admin.error-updating-admin-status': 'Fehler beim Aktualisieren des Admin-Status',
    'admin.error-verifying-bot': 'Fehler beim Verifizieren des Bots',
    'admin.error-deleting-bot': 'Fehler beim Löschen des Bots',
    'admin.error-deleting-server': 'Fehler beim Löschen des Servers',
    'admin.admin-status-updated': 'Admin-Status aktualisiert',
    'admin.user-is-now-admin': 'Benutzer ist jetzt Admin',
    'admin.user-no-longer-admin': 'Benutzer ist kein Admin mehr',
    'admin.bot-verified': 'Bot verifiziert',
    'admin.bot-verified-success': 'Bot wurde erfolgreich verifiziert',
    'admin.bot-deleted': 'Bot gelöscht',
    'admin.bot-deleted-success': 'Bot wurde erfolgreich gelöscht',
    'admin.server-deleted': 'Server gelöscht',
    'admin.server-deleted-success': 'Server wurde erfolgreich gelöscht',
    'admin.confirm-delete-bot': 'Sind Sie sicher, dass Sie diesen Bot löschen möchten?',
    'admin.confirm-delete-server': 'Sind Sie sicher, dass Sie diesen Server löschen möchten?',
    'admin.access-denied': 'Zugriff verweigert',
    'admin.no-admin-rights': 'Sie haben keine Admin-Rechte',
    'admin.actions': 'Aktionen',
    'admin.joined': 'Beigetreten',
    'admin.added': 'Hinzugefügt',
    'admin.no-users-found': 'Keine Benutzer gefunden',
    'admin.no-bots-found': 'Keine Bots gefunden',
    'admin.no-pending-bots': 'Keine ausstehenden Bots',
    'admin.no-servers-found': 'Keine Server gefunden',
    'admin.user-detailed-info': 'Detaillierte Informationen über den Benutzer',
    'admin.registered': 'Registriert',
    'admin.last-updated': 'Zuletzt aktualisiert',
    'admin.admin-status': 'Admin-Status',
    'admin.administrator': 'Administrator',
    'admin.regular-user': 'Normaler Benutzer',
    'admin.bot-management': 'Bot-Verwaltung',
    'admin.bot-review': 'Überprüfung und Genehmigung ausstehender Bots',
    
    // Account manager
    'account.title': 'Kontoverwaltung',
    'account.profile': 'Profil',
    'account.settings': 'Einstellungen',
    'account.security': 'Sicherheit',
    'account.connected': 'Verbundene Konten',
    'account.theme': 'Design',
    'account.theme.light': 'Heller Modus',
    'account.theme.dark': 'Dunkler Modus',
    'account.theme.system': 'Systemeinstellung',
    'account.language': 'Sprache',
    'account.save': 'Änderungen speichern',
    'account.delete': 'Konto löschen',
    
    // Footer
    'footer.privacy': 'Datenschutz',
    'footer.imprint': 'Impressum',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.contact': 'Kontakt',
    'footer.language': 'Sprache',
    'footer.rights': 'Alle Rechte vorbehalten',
    
    // Misc
    'misc.loading': 'Wird geladen...',
    'misc.error': 'Ein Fehler ist aufgetreten',
    'misc.success': 'Erfolg!',
    'misc.search': 'Suchen',
    'misc.save': 'Speichern',
    'misc.cancel': 'Abbrechen',
    'misc.delete': 'Löschen',
    'misc.edit': 'Bearbeiten',
    'misc.view': 'Ansehen',
    'misc.create': 'Erstellen',
    'misc.submit': 'Absenden',
    'misc.back': 'Zurück',
    'misc.next': 'Weiter',
    'misc.previous': 'Zurück',
    'misc.unknown': 'Unbekannt',
    'misc.back-to-bots': 'Zurück zu Bots',
    'misc.saving': 'Wird gespeichert...',
    
    // Cookie banner
    'cookie.title': 'Cookie-Hinweis',
    'cookie.description': 'Wir verwenden Cookies, um sicherzustellen, dass Sie die beste Erfahrung auf unserer Website haben.',
    'cookie.accept': 'Alle akzeptieren',
    'cookie.decline': 'Ablehnen',
    'cookie.preferences': 'Anpassen',
    'cookie.save_preferences': 'Einstellungen speichern',
    'cookie.customize_notice': 'Sie können Ihre Cookie-Einstellungen jederzeit anpassen.',
    'cookie.necessary': 'Notwendige Cookies',
    'cookie.necessary_description': 'Diese Cookies sind für das ordnungsgemäße Funktionieren der Website unerlässlich.',
    'cookie.analytics': 'Analyse-Cookies',
    'cookie.analytics_description': 'Diese Cookies helfen uns zu verstehen, wie Besucher mit der Website interagieren.',
    'cookie.preferences': 'Präferenz-Cookies',
    'cookie.preferences_description': 'Diese Cookies ermöglichen es der Website, sich an Ihre Entscheidungen zu erinnern.',
    'cookie.marketing': 'Marketing-Cookies',
    'cookie.marketing_description': 'Diese Cookies werden verwendet, um Besucher über Websites hinweg zu verfolgen.',
    
    // Profile
    'profile.title': 'Profil',
    'profile.edit': 'Profil bearbeiten',
    'profile.bots': 'Meine Bots',
    'profile.settings': 'Einstellungen',
    'profile.your-profile': 'Dein Profil',
    'profile.manage-details': 'Verwalte deine Profildetails',
    'profile.edit-profile': 'Profil bearbeiten',
    'profile.update-information': 'Aktualisiere deine Profilinformationen',
    'profile.username': 'Benutzername',
    'profile.username-placeholder': 'Gib deinen Benutzernamen ein',
    'profile.bio': 'Biografie',
    'profile.bio-placeholder': 'Erzähle uns etwas über dich',
    'profile.website': 'Webseite',
    'profile.website-placeholder': 'Deine Webseiten-URL',
    'profile.save-changes': 'Änderungen speichern',
    'profile.your-bots': 'Deine Bots',
    'profile.manage-bots': 'Verwalte deine Discord-Bots',
    'profile.view-bot': 'Bot anzeigen',
    
    // Legal
    'legal.imprint': 'Impressum',
    'legal.company-information': 'Unternehmensinformationen',
    'legal.company-name': 'Discord Bot Verzeichnis',
    'legal.company-address': 'Bot-Straße 123',
    'legal.company-city': 'Bot-Stadt, 10115',
    'legal.company-country': 'Botland',
    'legal.contact': 'Kontakt',
    'legal.email': 'E-Mail',
    'legal.phone': 'Telefon',
    'legal.registration': 'Registrierung',
    'legal.registration-text': 'Eingetragen im Handelsregister von Bot-Stadt. Registrierungsnummer: BOT123456',
    'legal.vat': 'Umsatzsteuer-ID',
    'legal.vat-text': 'Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz: DE123456789',
    'legal.responsible-content': 'Verantwortlich für den Inhalt',
    'legal.responsible-content-text': 'Verantwortlich für den Inhalt gemäß § 55 Abs. 2 RStV: Max Mustermann, Bot-Straße 123, Bot-Stadt, 10115 Botland',
    'legal.dispute-resolution': 'Streitbeilegung',
    'legal.dispute-resolution-text': 'Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: https://ec.europa.eu/consumers/odr. Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.',
    'legal.privacy-policy': 'Datenschutzerklärung',
    'legal.information-collection': 'Informationserfassung',
    'legal.information-collection-text': 'Wir sammeln Informationen, die Sie uns direkt bei der Registrierung eines Kontos, beim Hinzufügen von Bots oder bei der Interaktion mit unserer Plattform zur Verfügung stellen. Dazu gehören E-Mail-Adressen, Benutzernamen und Discord-IDs.',
    'legal.information-usage': 'Verwendung von Informationen',
    'legal.information-usage-text': 'Wir verwenden Informationen über Sie, um unsere Dienste bereitzustellen, zu warten und zu verbessern, neue Funktionen zu entwickeln und die Plattform und unsere Benutzer zu schützen.',
    'legal.information-protection': 'Informationsschutz',
    'legal.information-protection-text': 'Wir implementieren Maßnahmen, die darauf ausgelegt sind, die Sicherheit Ihrer persönlichen Daten zu gewährleisten. Allerdings ist keine Übertragungsmethode über das Internet zu 100% sicher.',
    'legal.cookie-usage': 'Cookie-Nutzung',
    'legal.cookie-usage-text': 'Wir verwenden Cookies und ähnliche Technologien, um Informationen darüber zu sammeln, wie Sie mit unseren Diensten interagieren, und um bestimmte Präferenzen zu speichern.',
    'legal.third-party-disclosure': 'Weitergabe an Dritte',
    'legal.third-party-disclosure-text': 'Wir verkaufen, handeln oder übertragen Ihre persönlich identifizierbaren Informationen nicht ohne Ihre Zustimmung an Dritte.',
    'legal.third-party-links': 'Links zu Drittanbietern',
    'legal.third-party-links-text': 'Unser Dienst kann Links zu Websites oder Diensten von Drittanbietern enthalten. Wir haben keine Kontrolle über und übernehmen keine Verantwortung für den Inhalt, die Datenschutzricht
