import { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const defaultTranslations = {
  en: {
    // General
    'misc.loading': 'Loading...',
    'misc.error': 'An error occurred',
    'misc.submit': 'Submit',
    'misc.cancel': 'Cancel',
    'misc.save': 'Save',
    'misc.delete': 'Delete',
    'misc.edit': 'Edit',
    'misc.back': 'Back',
    'misc.next': 'Next',
    'misc.or': 'Or',
    'misc.required': 'Required',
    'misc.optional': 'Optional',
    'misc.yes': 'Yes',
    'misc.no': 'No',
    'misc.search': 'Search',
    'misc.filter': 'Filter',
    'misc.reset': 'Reset',
    'misc.confirm': 'Confirm',
    'misc.continue': 'Continue',
    'misc.success': 'Success!',
    'misc.copied': 'Copied to clipboard!',
    
    // Navigation
    'nav.home': 'Home',
    'nav.servers': 'Servers',
    'nav.bots': 'Bots',
    'nav.add-bot': 'Add Bot',
    'nav.add-server': 'Add Server',
    'nav.profile': 'Profile',
    'nav.account': 'Account',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.register': 'Register',
    'nav.terms': 'Terms',
    'nav.privacy': 'Privacy',
    'nav.imprint': 'Imprint',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgot-password': 'Forgot Password?',
    'auth.reset-password': 'Reset Password',
    'auth.reset-password-sent': 'If your email is registered, you will receive a password reset link.',
    'auth.no-account': 'Don\'t have an account?',
    'auth.have-account': 'Already have an account?',
    'auth.sign-up': 'Sign Up',
    'auth.sign-in': 'Sign In',
    'auth.sign-out': 'Sign Out',
    'auth.continue-with': 'Continue with {provider}',
    'auth.discord': 'Discord',
    'auth.google': 'Google',
    'auth.github': 'GitHub',
    'auth.error': 'Authentication error',
    'auth.username': 'Username',
    'auth.welcome': 'Welcome to Bot Finder Hub!',
    'auth.description': 'Your central platform for managing Discord bots and servers.',
    'auth.login-description': 'Login to manage your bots and servers.',
    'auth.register-description': 'Create an account to start adding your bots and servers.',
    'auth.confirm-email': 'Please check your email to confirm your account.',
    'auth.logout-confirm': 'Are you sure you want to log out?',
    'auth.login-required': 'You must be logged in to access this page.',
    
    // Profile
    'profile.title': 'Your Profile',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Profile',
    'profile.avatar': 'Avatar',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.bio': 'Bio',
    'profile.website': 'Website',
    'profile.joined': 'Joined',
    'profile.your-bots': 'Your Bots',
    'profile.your-servers': 'Your Servers',
    'profile.no-bots': 'You haven\'t added any bots yet.',
    'profile.no-servers': 'You haven\'t added any servers yet.',
    'profile.updated': 'Profile updated successfully!',
    'profile.error': 'Failed to update profile.',
    
    // Account
    'account.title': 'Account Settings',
    'account.general': 'General Settings',
    'account.security': 'Security',
    'account.appearance': 'Appearance',
    'account.notifications': 'Notifications',
    'account.danger': 'Danger Zone',
    'account.delete': 'Delete Account',
    'account.delete-confirm': 'Are you sure you want to delete your account? This action cannot be undone.',
    'account.password-change': 'Change Password',
    'account.current-password': 'Current Password',
    'account.new-password': 'New Password',
    'account.confirm-password': 'Confirm New Password',
    'account.password-updated': 'Password updated successfully!',
    'account.password-error': 'Failed to update password.',
    'account.theme': 'Theme',
    'account.theme-light': 'Light',
    'account.theme-dark': 'Dark',
    'account.theme-system': 'System',
    'account.language': 'Language',
    'account.language-en': 'English',
    'account.language-de': 'Deutsch',
    
    // Home
    'home.hero-title': 'Find the Perfect Discord Bots and Servers',
    'home.hero-subtitle': 'Discover, add, and manage Discord bots and servers all in one place.',
    'home.get-started': 'Get Started',
    'home.explore-bots': 'Explore Bots',
    'home.explore-servers': 'Explore Servers',
    'home.how-it-works': 'How It Works',
    'home.features': 'Features',
    'home.feature-1-title': 'Bot Directory',
    'home.feature-1-desc': 'Browse and discover Discord bots for your server.',
    'home.feature-2-title': 'Server Showcase',
    'home.feature-2-desc': 'Find active Discord communities to join.',
    'home.feature-3-title': 'Easy Management',
    'home.feature-3-desc': 'Manage your bots and servers in one place.',
    'home.featured-bots': 'Featured Bots',
    'home.popular-servers': 'Popular Servers',
    'home.view-all-bots': 'View All Bots',
    'home.view-all-servers': 'View All Servers',
    
    // Bot
    'bot.add': 'Add Bot',
    'bot.edit': 'Edit Bot',
    'bot.delete': 'Delete Bot',
    'bot.delete-confirm': 'Are you sure you want to delete this bot? This action cannot be undone.',
    'bot.name': 'Bot Name',
    'bot.prefix': 'Command Prefix',
    'bot.invite': 'Invite Bot',
    'bot.support': 'Support Server',
    'bot.website': 'Website',
    'bot.github': 'GitHub',
    'bot.description': 'Description',
    'bot.short-description': 'Short Description',
    'bot.tags': 'Tags',
    'bot.owner': 'Owner',
    'bot.created': 'Created',
    'bot.updated': 'Last Updated',
    'bot.id': 'Bot ID',
    'bot.invite-url': 'Invite URL',
    'bot.support-url': 'Support URL',
    'bot.website-url': 'Website URL',
    'bot.github-url': 'GitHub URL',
    'bot.image-url': 'Avatar URL',
    'bot.verified': 'Verified',
    'bot.stars': 'Stars',
    'bot.star': 'Star',
    'bot.unstar': 'Unstar',
    'bot.add-success': 'Bot added successfully!',
    'bot.edit-success': 'Bot updated successfully!',
    'bot.delete-success': 'Bot deleted successfully!',
    'bot.star-success': 'Bot starred successfully!',
    'bot.unstar-success': 'Bot unstarred successfully!',
    'bot.error': 'Failed to process your request.',
    'bot.no-description': 'No description provided.',
    'bot.verify': 'Verify Bot',
    'bot.verify-submit': 'Submit for Verification',
    'bot.verify-cancel': 'Cancel Verification',
    'bot.verify-success': 'Bot submitted for verification!',
    'bot.verify-cancel-success': 'Verification canceled!',
    'bot.bump': 'Bump',
    'bot.bumping': 'Bumping...',
    'bot.bump-success': 'Bot bumped successfully!',
    'bot.bump-error': 'Failed to bump bot.',
    'bot.view-details': 'View Details',
    'bot.discord-id': 'Discord ID',
    'bot.feedback': 'Feedback',
    'bot.review': 'Review',
    'bot.reviews': 'Reviews',
    'bot.write-review': 'Write a Review',
    'bot.your-review': 'Your Review',
    'bot.rating': 'Rating',
    'bot.comment': 'Comment',
    'bot.submit-review': 'Submit Review',
    'bot.edit-review': 'Edit Review',
    'bot.delete-review': 'Delete Review',
    'bot.review-success': 'Review submitted successfully!',
    'bot.review-edit-success': 'Review updated successfully!',
    'bot.review-delete-success': 'Review deleted successfully!',
    'bot.no-reviews': 'No reviews yet.',
    'bot.directory': 'Bot Directory',
    'bot.directory-desc': 'Browse and discover Discord bots for your server.',
    'bot.none-found': 'No bots found.',
    'bot.be-first': 'Be the first to add your bot to our directory!',
    'bot.add-yours': 'Add Your Bot',
    'bot.last-updated': 'Last updated',
    
    // Server
    'server.add': 'Add Server',
    'server.edit': 'Edit Server',
    'server.delete': 'Delete Server',
    'server.delete-confirm': 'Are you sure you want to delete this server? This action cannot be undone.',
    'server.name': 'Server Name',
    'server.invite': 'Invite Link',
    'server.description': 'Description',
    'server.tags': 'Tags',
    'server.owner': 'Owner',
    'server.created': 'Created',
    'server.updated': 'Last Updated',
    'server.id': 'Server ID',
    'server.members': 'Members',
    'server.icon-url': 'Icon URL',
    'server.invite-url': 'Invite URL',
    'server.add-success': 'Server added successfully!',
    'server.edit-success': 'Server updated successfully!',
    'server.delete-success': 'Server deleted successfully!',
    'server.error': 'Failed to process your request.',
    'server.no-description': 'No description provided.',
    'server.join': 'Join Server',
    'server.bump': 'Bump',
    'server.bumping': 'Bumping...',
    'server.bump-success': 'Server bumped successfully!',
    'server.bump-error': 'Failed to bump server.',
    'server.view-details': 'View Details',
    'server.directory': 'Server Directory',
    'server.directory-desc': 'Browse and discover Discord servers to join.',
    'server.none-found': 'No servers found.',
    'server.be-first': 'Be the first to add your server to our directory!',
    'server.add-yours': 'Add Your Server',
    
    // Cookie
    'cookie.title': 'Cookie Settings',
    'cookie.description': 'We use cookies to improve your experience on our site.',
    'cookie.accept': 'Accept All',
    'cookie.decline': 'Decline All',
    'cookie.preferences': 'Preferences',
    'cookie.save_preferences': 'Save Preferences',
    'cookie.necessary': 'Necessary Cookies',
    'cookie.necessary_description': 'Essential cookies that enable core functionality of the website.',
    'cookie.analytics': 'Analytics Cookies',
    'cookie.analytics_description': 'Cookies that help us understand how you interact with our website.',
    'cookie.preferences': 'Preference Cookies',
    'cookie.preferences_description': 'Cookies that remember your preferences and settings.',
    'cookie.marketing': 'Marketing Cookies',
    'cookie.marketing_description': 'Cookies used to deliver advertisements relevant to you.',
    'cookie.customize_notice': 'You can customize which cookies to accept.',
    
    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.imprint': 'Imprint',
    'footer.discord': 'Join our Discord',
    'footer.github': 'GitHub',
    'footer.twitter': 'Twitter',
    'footer.contact': 'Contact Us',
    'footer.about': 'About Us',
    'footer.copyright': '© 2025 Bot Finder Hub.',

    // Admin
    'admin.dashboard': 'Admin Dashboard',
    'admin.overview': 'Overview',
    'admin.users': 'Users',
    'admin.bots': 'Bots',
    'admin.servers': 'Servers',
    'admin.pending': 'Pending Verification',
    'admin.settings': 'Settings',
    'admin.stats': 'Statistics',
    'admin.total-users': 'Total Users',
    'admin.total-bots': 'Total Bots',
    'admin.total-servers': 'Total Servers',
    'admin.verified-bots': 'Verified Bots',
    'admin.pending-verification': 'Pending Verification',
    'admin.verification-required': 'Verification Required',
    'admin.user-management': 'User Management',
    'admin.manage-users-permissions': 'Manage Users & Permissions',
    'admin.bot-management': 'Bot Management',
    'admin.no-bots-found': 'No bots found',
    'admin.bot-review': 'Bot Review',
    'admin.no-pending-bots': 'No pending bots',
    'admin.actions': 'Actions',
    'admin.view': 'View',
    'admin.verify': 'Verify',
    'admin.reject': 'Reject',
    'admin.error-fetching-users': 'Error fetching users',
    'admin.error-fetching-bots': 'Error fetching bots',
    'admin.confirm-verify': 'Are you sure you want to verify this bot?',
    'admin.confirm-reject': 'Are you sure you want to reject this bot?',
    'admin.verify-success': 'Bot verified successfully',
    'admin.reject-success': 'Bot rejected successfully',
    'admin.error': 'An error occurred',
  },
  de: {
    // General
    'misc.loading': 'Laden...',
    'misc.error': 'Ein Fehler ist aufgetreten',
    'misc.submit': 'Absenden',
    'misc.cancel': 'Abbrechen',
    'misc.save': 'Speichern',
    'misc.delete': 'Löschen',
    'misc.edit': 'Bearbeiten',
    'misc.back': 'Zurück',
    'misc.next': 'Weiter',
    'misc.or': 'Oder',
    'misc.required': 'Erforderlich',
    'misc.optional': 'Optional',
    'misc.yes': 'Ja',
    'misc.no': 'Nein',
    'misc.search': 'Suchen',
    'misc.filter': 'Filtern',
    'misc.reset': 'Zurücksetzen',
    'misc.confirm': 'Bestätigen',
    'misc.continue': 'Fortfahren',
    'misc.success': 'Erfolg!',
    'misc.copied': 'In die Zwischenablage kopiert!',
    
    // Navigation
    'nav.home': 'Startseite',
    'nav.servers': 'Server',
    'nav.bots': 'Bots',
    'nav.add-bot': 'Bot hinzufügen',
    'nav.add-server': 'Server hinzufügen',
    'nav.profile': 'Profil',
    'nav.account': 'Konto',
    'nav.admin': 'Admin',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',
    'nav.register': 'Registrieren',
    'nav.terms': 'AGB',
    'nav.privacy': 'Datenschutz',
    'nav.imprint': 'Impressum',
    
    // Auth
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.forgot-password': 'Passwort vergessen?',
    'auth.reset-password': 'Passwort zurücksetzen',
    'auth.reset-password-sent': 'Wenn Ihre E-Mail registriert ist, erhalten Sie einen Link zum Zurücksetzen des Passworts.',
    'auth.no-account': 'Noch kein Konto?',
    'auth.have-account': 'Bereits ein Konto?',
    'auth.sign-up': 'Registrieren',
    'auth.sign-in': 'Anmelden',
    'auth.sign-out': 'Abmelden',
    'auth.continue-with': 'Fortfahren mit {provider}',
    'auth.discord': 'Discord',
    'auth.google': 'Google',
    'auth.github': 'GitHub',
    'auth.error': 'Authentifizierungsfehler',
    'auth.username': 'Benutzername',
    'auth.welcome': 'Willkommen bei Bot Finder Hub!',
    'auth.description': 'Deine zentrale Plattform zur Verwaltung von Discord-Bots und Servern.',
    'auth.login-description': 'Melde dich an, um deine Bots und Server zu verwalten.',
    'auth.register-description': 'Erstelle ein Konto, um deine Bots und Server hinzuzufügen.',
    'auth.confirm-email': 'Bitte überprüfe deine E-Mail, um dein Konto zu bestätigen.',
    'auth.logout-confirm': 'Bist du sicher, dass du dich abmelden möchtest?',
    'auth.login-required': 'Du musst angemeldet sein, um auf diese Seite zuzugreifen.',
    
    // Profile
    'profile.title': 'Dein Profil',
    'profile.edit': 'Profil bearbeiten',
    'profile.save': 'Profil speichern',
    'profile.avatar': 'Avatar',
    'profile.username': 'Benutzername',
    'profile.email': 'E-Mail',
    'profile.bio': 'Bio',
    'profile.website': 'Webseite',
    'profile.joined': 'Beigetreten',
    'profile.your-bots': 'Deine Bots',
    'profile.your-servers': 'Deine Server',
    'profile.no-bots': 'Du hast noch keine Bots hinzugefügt.',
    'profile.no-servers': 'Du hast noch keine Server hinzugefügt.',
    'profile.updated': 'Profil erfolgreich aktualisiert!',
    'profile.error': 'Fehler beim Aktualisieren des Profils.',
    
    // Account
    'account.title': 'Kontoeinstellungen',
    'account.general': 'Allgemeine Einstellungen',
    'account.security': 'Sicherheit',
    'account.appearance': 'Erscheinungsbild',
    'account.notifications': 'Benachrichtigungen',
    'account.danger': 'Gefahrenzone',
    'account.delete': 'Konto löschen',
    'account.delete-confirm': 'Bist du sicher, dass du dein Konto löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.',
    'account.password-change': 'Passwort ändern',
    'account.current-password': 'Aktuelles Passwort',
    'account.new-password': 'Neues Passwort',
    'account.confirm-password': 'Neues Passwort bestätigen',
    'account.password-updated': 'Passwort erfolgreich aktualisiert!',
    'account.password-error': 'Fehler beim Aktualisieren des Passworts.',
    'account.theme': 'Design',
    'account.theme-light': 'Hell',
    'account.theme-dark': 'Dunkel',
    'account.theme-system': 'System',
    'account.language': 'Sprache',
    'account.language-en': 'Englisch',
    'account.language-de': 'Deutsch',
    
    // Home
    'home.hero-title': 'Finde die perfekten Discord-Bots und Server',
    'home.hero-subtitle': 'Entdecke, füge hinzu und verwalte Discord-Bots und Server an einem Ort.',
    'home.get-started': 'Loslegen',
    'home.explore-bots': 'Bots entdecken',
    'home.explore-servers': 'Server entdecken',
    'home.how-it-works': 'Wie es funktioniert',
    'home.features': 'Funktionen',
    'home.feature-1-title': 'Bot-Verzeichnis',
    'home.feature-1-desc': 'Durchsuche und entdecke Discord-Bots für deinen Server.',
    'home.feature-2-title': 'Server-Showcase',
    'home.feature-2-desc': 'Finde aktive Discord-Communities zum Beitreten.',
    'home.feature-3-title': 'Einfache Verwaltung',
    'home.feature-3-desc': 'Verwalte deine Bots und Server an einem Ort.',
    'home.featured-bots': 'Empfohlene Bots',
    'home.popular-servers': 'Beliebte Server',
    'home.view-all-bots': 'Alle Bots anzeigen',
    'home.view-all-servers': 'Alle Server anzeigen',
    
    // Bot
    'bot.add': 'Bot hinzufügen',
    'bot.edit': 'Bot bearbeiten',
    'bot.delete': 'Bot löschen',
    'bot.delete-confirm': 'Bist du sicher, dass du diesen Bot löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.',
    'bot.name': 'Bot-Name',
    'bot.prefix': 'Befehlspräfix',
    'bot.invite': 'Bot einladen',
    'bot.support': 'Support-Server',
    'bot.website': 'Webseite',
    'bot.github': 'GitHub',
    'bot.description': 'Beschreibung',
    'bot.short-description': 'Kurzbeschreibung',
    'bot.tags': 'Tags',
    'bot.owner': 'Besitzer',
    'bot.created': 'Erstellt',
    'bot.updated': 'Zuletzt aktualisiert',
    'bot.id': 'Bot-ID',
    'bot.invite-url': 'Einladungs-URL',
    'bot.support-url': 'Support-URL',
    'bot.website-url': 'Webseiten-URL',
    'bot.github-url': 'GitHub-URL',
    'bot.image-url': 'Avatar-URL',
    'bot.verified': 'Verifiziert',
    'bot.stars': 'Sterne',
    'bot.star': 'Stern geben',
    'bot.unstar': 'Stern entfernen',
    'bot.add-success': 'Bot erfolgreich hinzugefügt!',
    'bot.edit-success': 'Bot erfolgreich aktualisiert!',
    'bot.delete-success': 'Bot erfolgreich gelöscht!',
    'bot.star-success': 'Bot erfolgreich mit Stern markiert!',
    'bot.unstar-success': 'Stern erfolgreich vom Bot entfernt!',
    'bot.error': 'Fehler bei der Verarbeitung deiner Anfrage.',
    'bot.no-description': 'Keine Beschreibung vorhanden.',
    'bot.verify': 'Bot verifizieren',
    'bot.verify-submit': 'Zur Verifizierung einreichen',
    'bot.verify-cancel': 'Verifizierung abbrechen',
    'bot.verify-success': 'Bot zur Verifizierung eingereicht!',
    'bot.verify-cancel-success': 'Verifizierung abgebrochen!',
    'bot.bump': 'Bumpen',
    'bot.bumping': 'Bumping...',
    'bot.bump-success': 'Bot erfolgreich gebumpt!',
    'bot.bump-error': 'Fehler beim Bumpen des Bots.',
    'bot.view-details': 'Details anzeigen',
    'bot.discord-id': 'Discord-ID',
    'bot.feedback': 'Feedback',
    'bot.review': 'Bewertung',
    'bot.reviews': 'Bewertungen',
    'bot.write-review': 'Bewertung schreiben',
    'bot.your-review': 'Deine Bewertung',
    'bot.rating': 'Bewertung',
    'bot.comment': 'Kommentar',
    'bot.submit-review': 'Bewertung absenden',
    'bot.edit-review': 'Bewertung bearbeiten',
    'bot.delete-review': 'Bewertung löschen',
    'bot.review-success': 'Bewertung erfolgreich abgesendet!',
    'bot.review-edit-success': 'Bewertung erfolgreich aktualisiert!',
    'bot.review-delete-success': 'Bewertung erfolgreich gelöscht!',
    'bot.no-reviews': 'Noch keine Bewertungen.',
    'bot.directory': 'Bot-Verzeichnis',
    'bot.directory-desc': 'Durchsuche und entdecke Discord-Bots für deinen Server.',
    'bot.none-found': 'Keine Bots gefunden.',
    'bot.be-first': 'Sei der Erste, der seinen Bot zu unserem Verzeichnis hinzufügt!',
    'bot.add-yours': 'Deinen Bot hinzufügen',
    'bot.last-updated': 'Zuletzt aktualisiert',
    
    // Server
    'server.add': 'Server hinzufügen',
    'server.edit': 'Server bearbeiten',
    'server.delete': 'Server löschen',
    'server.delete-confirm': 'Bist du sicher, dass du diesen Server löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden.',
    'server.name': 'Server-Name',
    'server.invite': 'Einladungslink',
    'server.description': 'Beschreibung',
    'server.tags': 'Tags',
    'server.owner': 'Besitzer',
    'server.created': 'Erstellt',
    'server.updated': 'Zuletzt aktualisiert',
    'server.id': 'Server-ID',
    'server.members': 'Mitglieder',
    'server.icon-url': 'Icon-URL',
    'server.invite-url': 'Einladungs-URL',
    'server.add-success': 'Server erfolgreich hinzugefügt!',
    'server.edit-success': 'Server erfolgreich aktualisiert!',
    'server.delete-success': 'Server erfolgreich gelöscht!',
    'server.error': 'Fehler bei der Verarbeitung deiner Anfrage.',
    'server.no-description': 'Keine Beschreibung vorhanden.',
    'server.join': 'Server beitreten',
    'server.bump': 'Bumpen',
    'server.bumping': 'Bumping...',
    'server.bump-success': 'Server erfolgreich gebumpt!',
    'server.bump-error': 'Fehler beim Bumpen des Servers.',
    'server.view-details': 'Details anzeigen',
    'server.directory': 'Server-Verzeichnis',
    'server.directory-desc': 'Durchsuche und entdecke Discord-Server zum Beitreten.',
    'server.none-found': 'Keine Server gefunden.',
    'server.be-first': 'Sei der Erste, der seinen Server zu unserem Verzeichnis hinzufügt!',
    'server.add-yours': 'Deinen Server hinzufügen',
    
    // Cookie
    'cookie.title': 'Cookie-Einstellungen',
    'cookie.description': 'Wir verwenden Cookies, um deine Erfahrung auf unserer Seite zu verbessern.',
    'cookie.accept': 'Alle akzeptieren',
    'cookie.decline': 'Alle ablehnen',
    'cookie.preferences': 'Einstellungen',
    'cookie.save_preferences': 'Einstellungen speichern',
    'cookie.necessary': 'Notwendige Cookies',
    'cookie.necessary_description': 'Essentielle Cookies, die die Kernfunktionalität der Website ermöglichen.',
    'cookie.analytics': 'Analyse-Cookies',
    'cookie.analytics_description': 'Cookies, die uns helfen zu verstehen, wie du mit unserer Website interagierst.',
    'cookie.preferences': 'Präferenz-Cookies',
    'cookie.preferences_description': 'Cookies, die deine Präferenzen und Einstellungen speichern.',
    'cookie.marketing': 'Marketing-Cookies',
    'cookie.marketing_description': 'Cookies, die verwendet werden, um relevante Werbung für dich bereitzustellen.',
    'cookie.customize_notice': 'Du kannst anpassen, welche Cookies du akzeptierst.',
    
    // Footer
    'footer.rights': 'Alle Rechte vorbehalten.',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.imprint': 'Impressum',
    'footer.discord': 'Tritt unserem Discord bei',
    'footer.github': 'GitHub',
    'footer.twitter': 'Twitter',
    'footer.contact': 'Kontaktiere uns',
    'footer.about': 'Über uns',
    'footer.copyright': '© 2025 Bot Finder Hub.',

    // Admin
    'admin.dashboard': 'Admin-Dashboard',
    'admin.overview': 'Übersicht',
    'admin.users': 'Benutzer',
    'admin.bots': 'Bots',
    'admin.servers': 'Server',
    'admin.pending': 'Ausstehende Verifizierung',
    'admin.settings': 'Einstellungen',
    'admin.stats': 'Statistiken',
    'admin.total-users': 'Gesamtbenutzer',
    'admin.total-bots': 'Gesamtbots',
    'admin.total-servers': 'Gesamtserver',
    'admin.verified-bots': 'Verifizierte Bots',
    'admin.pending-verification': 'Ausstehende Verifizierung',
    'admin.verification-required': 'Verifizierung erforderlich',
    'admin.user-management': 'Benutzerverwaltung',
    'admin.manage-users-permissions': 'Benutzer & Berechtigungen verwalten',
    'admin.bot-management': 'Bot-Verwaltung',
    'admin.no-bots-found': 'Keine Bots gefunden',
    'admin.bot-review': 'Bot-Überprüfung',
    'admin.no-pending-bots': 'Keine ausstehenden Bots',
    'admin.actions': 'Aktionen',
    'admin.view': 'Ansehen',
    'admin.verify': 'Verifizieren',
    'admin.reject': 'Ablehnen',
    'admin.error-fetching-users': 'Fehler beim Abrufen der Benutzer',
    'admin.error-fetching-bots': 'Fehler beim Abrufen der Bots',
    'admin.confirm-verify': 'Bist du sicher, dass du diesen Bot verifizieren möchtest?',
    'admin.confirm-reject': 'Bist du sicher, dass du diesen Bot ablehnen möchtest?',
    'admin.verify-success': 'Bot erfolgreich verifiziert',
    'admin.reject-success': 'Bot erfolgreich abgelehnt',
    'admin.error': 'Ein Fehler ist aufgetreten',
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: () => '',
});

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState('en');
  
  const t = (key: string): string => {
    const translations = defaultTranslations[language as keyof typeof defaultTranslations] || defaultTranslations.en;
    return translations[key as keyof typeof translations] || key;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
