
import React, { createContext, useContext, useState, useEffect } from 'react';

// Define the supported languages
export type Language = 'en' | 'de' | 'es';

// Language context type
interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.bots': 'Bots',
    'nav.add-bot': 'Add Bot',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.login': 'Log In',
    'nav.register': 'Register',
    'nav.logout': 'Log Out',
    'nav.search': 'Search',
    'nav.servers': 'Servers',
    'nav.add-server': 'Add Server',
    'nav.account': 'Account',
    
    // Home page
    'home.title': 'Discover Discord Bots',
    'home.subtitle': 'Find the perfect bot for your Discord server',
    'home.search-placeholder': 'Search by name, category, or feature',
    'home.explore': 'Explore Bots',
    'home.popular': 'Popular Bots',
    'home.recent': 'Recently Added',
    'home.featured': 'Featured Bots',
    
    // Auth
    'auth.login': 'Log In',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm-password': 'Confirm Password',
    'auth.username': 'Username',
    'auth.username-placeholder': 'Enter your username',
    'auth.forgot-password': 'Forgot Password?',
    'auth.already-account': 'Already have an account?',
    'auth.no-account': 'Don\'t have an account?',
    'auth.or': 'or',
    'auth.login-with-google': 'Log in with Google',
    'auth.register-with-google': 'Register with Google',
    'auth.login-with-discord': 'Log in with Discord',
    'auth.register-with-discord': 'Register with Discord',
    'auth.login-description': 'Sign in to your account to manage your bots and servers',
    'auth.register-description': 'Create an account to add your bots and servers to our directory',
    
    // Bot details
    'bot.add': 'Add Bot',
    'bot.edit': 'Edit Bot',
    'bot.delete': 'Delete Bot',
    'bot.name': 'Bot Name',
    'bot.description': 'Description',
    'bot.id': 'Bot ID',
    'bot.prefix': 'Prefix',
    'bot.category': 'Category',
    'bot.website': 'Website',
    'bot.invite': 'Invite Bot',
    'bot.support': 'Support Server',
    'bot.github': 'GitHub Repository',
    'bot.tags': 'Tags',
    'bot.save': 'Save Bot',
    'bot.cancel': 'Cancel',
    'bot.owner': 'Owner',
    'bot.created': 'Created',
    'bot.updated': 'Updated',
    'bot.stars': 'stars',
    'bot.verified': 'Verified',
    'bot.no-description': 'No description provided',
    'bot.unknown': 'Unknown',
    'bot.not-found': 'Bot Not Found',
    'bot.not-found-description': 'The bot you\'re looking for doesn\'t exist or has been removed.',
    'bot.back-to-bots': 'Back to Bots',
    'bot.view-details': 'View Details',
    'bot.directory': 'Bot Directory',
    'bot.directory-desc': 'Browse and discover Discord bots for your server',
    'bot.none-found': 'No bots found',
    'bot.be-first': 'Be the first to add a bot!',
    'bot.add-yours': 'Add Your Bot',
    'bot.last-updated': 'Last Updated',
    'bot.bump': 'Bump',
    'bot.bumping': 'Bumping...',
    
    // Server
    'server.add': 'Add Server',
    'server.edit': 'Edit Server',
    'server.delete': 'Delete Server',
    'server.name': 'Server Name',
    'server.description': 'Description',
    'server.invite': 'Invite Link',
    'server.members': 'Members',
    'server.join': 'Join Server',
    'server.tags': 'Tags',
    
    // Admin
    'admin.title': 'Admin Panel',
    'admin.users': 'Users',
    'admin.bots': 'Bots',
    'admin.reports': 'Reports',
    'admin.settings': 'Settings',
    'admin.pending': 'Pending Bots',
    'admin.servers': 'Discord Servers',
    'admin.overview': 'Overview',
    'admin.user-management': 'User Management',
    'admin.verified-bots': 'Verified Bots',
    'admin.pending-bots': 'Pending Verification',
    'admin.server-management': 'Server Management',
    'admin.total-users': 'Total Users',
    'admin.total-bots': 'Total Bots',
    'admin.total-servers': 'Total Servers',
    'admin.pending-verification': 'Pending Verification',
    'admin.registered-users': 'Registered Users',
    'admin.verification-required': 'Verification Required',
    'admin.refresh': 'Refresh',
    'admin.approve': 'Approve',
    'admin.decline': 'Decline',
    'admin.remove-admin': 'Remove Admin Rights',
    'admin.make-admin': 'Make Admin',
    'admin.last-updated': 'Last Updated',
    'admin.user-details': 'User Details',
    'admin.close': 'Close',
    'admin.error-fetching-bots': 'Error fetching bots',
    
    // Account manager
    'account.title': 'Account Manager',
    'account.profile': 'Profile',
    'account.settings': 'Settings',
    'account.security': 'Security',
    'account.connected': 'Connected Accounts',
    'account.theme': 'Theme',
    'account.theme.light': 'Light Mode',
    'account.theme.dark': 'Dark Mode',
    'account.theme.system': 'System Default',
    'account.language': 'Language',
    'account.save': 'Save Changes',
    'account.delete': 'Delete Account',
    
    // Footer
    'footer.privacy': 'Privacy Policy',
    'footer.imprint': 'Imprint',
    'footer.terms': 'Terms of Service',
    'footer.contact': 'Contact',
    'footer.language': 'Language',
    
    // Misc
    'misc.loading': 'Loading...',
    'misc.error': 'An error occurred',
    'misc.success': 'Success!',
    'misc.search': 'Search',
    'misc.save': 'Save',
    'misc.cancel': 'Cancel',
    'misc.delete': 'Delete',
    'misc.edit': 'Edit',
    'misc.view': 'View',
    'misc.create': 'Create',
    'misc.submit': 'Submit',
    'misc.back': 'Back',
    'misc.next': 'Next',
    'misc.previous': 'Previous',
    'misc.unknown': 'Unknown',
    'misc.back-to-bots': 'Back to Bots',
    'misc.saving': 'Saving...',
    
    // Cookie banner
    'cookie.title': 'Cookie Notice',
    'cookie.description': 'We use cookies to ensure you get the best experience on our website.',
    'cookie.accept': 'Accept All',
    'cookie.decline': 'Decline',
    'cookie.preferences': 'Customize',
    
    // Profile
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.bots': 'My Bots',
    'profile.settings': 'Settings',
    'profile.your-profile': 'Your Profile',
    'profile.manage-details': 'Manage your profile details',
    'profile.edit-profile': 'Edit Profile',
    'profile.update-information': 'Update your profile information',
    'profile.username': 'Username',
    'profile.username-placeholder': 'Enter your username',
    'profile.bio': 'Bio',
    'profile.bio-placeholder': 'Tell us about yourself',
    'profile.website': 'Website',
    'profile.website-placeholder': 'Your website URL',
    'profile.save-changes': 'Save Changes',
    'profile.your-bots': 'Your Bots',
    'profile.manage-bots': 'Manage your Discord bots',
    'profile.view-bot': 'View Bot',
    
    // Legal
    'legal.imprint': 'Imprint',
    'legal.company-information': 'Company Information',
    'legal.company-name': 'Discord Bot Directory',
    'legal.company-address': '123 Bot Street',
    'legal.company-city': 'Bot City, 10115',
    'legal.company-country': 'Botland',
    'legal.contact': 'Contact',
    'legal.email': 'Email',
    'legal.phone': 'Phone',
    'legal.registration': 'Registration',
    'legal.registration-text': 'Registered in the Commercial Register of Bot City. Registration Number: BOT123456',
    'legal.vat': 'VAT',
    'legal.vat-text': 'VAT Identification Number according to § 27a of the Value Added Tax Act: DE123456789',
    'legal.responsible-content': 'Responsible for Content',
    'legal.responsible-content-text': 'Person responsible for content in accordance with § 55 Abs. 2 RStV: John Doe, 123 Bot Street, Bot City, 10115 Botland',
    'legal.dispute-resolution': 'Dispute Resolution',
    'legal.dispute-resolution-text': 'The European Commission provides a platform for online dispute resolution (OS): https://ec.europa.eu/consumers/odr. We are not willing or obliged to participate in dispute resolution proceedings before a consumer arbitration board.',
    'legal.privacy-policy': 'Privacy Policy',
    'legal.information-collection': 'Information Collection',
    'legal.information-collection-text': 'We collect information you provide directly to us when registering for an account, adding bots, or interacting with our platform. This includes email addresses, usernames, and Discord IDs.',
    'legal.information-usage': 'Information Usage',
    'legal.information-usage-text': 'We use information about you to provide, maintain, and improve our services, develop new features, and protect the platform and our users.',
    'legal.information-protection': 'Information Protection',
    'legal.information-protection-text': 'We implement measures designed to ensure the security of your personal information. However, no method of transmission over the Internet is 100% secure.',
    'legal.cookie-usage': 'Cookie Usage',
    'legal.cookie-usage-text': 'We use cookies and similar technologies to collect information about how you interact with our services and to remember certain preferences.',
    'legal.third-party-disclosure': 'Third-Party Disclosure',
    'legal.third-party-disclosure-text': 'We do not sell, trade, or otherwise transfer your personally identifiable information to outside parties without your consent.',
    'legal.third-party-links': 'Third-Party Links',
    'legal.third-party-links-text': 'Our service may contain links to third-party websites or services. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services.',
    'legal.gdpr-compliance': 'GDPR Compliance',
    'legal.gdpr-compliance-text': 'For users in the European Union, we provide rights regarding your personal data, including the right to access, correct, or delete your personal information.',
    'legal.childrens-privacy': 'Children\'s Privacy',
    'legal.childrens-privacy-text': 'Our services are not directed to anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13.',
    'legal.changes-to-policy': 'Changes to Policy',
    'legal.changes-to-policy-text': 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.',
    'legal.contact-us': 'Contact Us',
    'legal.contact-us-text': 'If you have any questions about this Privacy Policy, please contact us through the platform or via the provided contact information.',
    'legal.terms-of-service': 'Terms of Service',
    'legal.acceptance': 'Acceptance of Terms',
    'legal.terms-acceptance-text': 'By accessing and using this Discord Bot Directory, you accept and agree to be bound by the terms and provisions of this agreement.',
    'legal.eligibility': 'Eligibility',
    'legal.eligibility-text': 'To use our services, you must be at least 13 years of age and comply with Discord\'s Terms of Service.',
    'legal.user-accounts': 'User Accounts',
    'legal.user-accounts-text': 'Users are responsible for maintaining the security of their account and password. The platform cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.',
    'legal.user-content': 'User Content',
    'legal.user-content-text': 'You are responsible for all content and activity that occurs under your account. Harmful or abusive content is strictly prohibited.',
    'legal.prohibited-conduct': 'Prohibited Conduct',
    'legal.prohibited-conduct-text': 'Users may not engage in any activity that interferes with or disrupts the services or servers connected to the platform.',
    'legal.intellectual-property': 'Intellectual Property',
    'legal.intellectual-property-text': 'The service and its original content, features, and functionality are owned by the platform and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.',
    'legal.termination': 'Termination',
    'legal.termination-text': 'We may terminate or suspend your account and bar access to the service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation.',
    'legal.disclaimer': 'Disclaimer',
    'legal.disclaimer-text': 'Your use of the service is at your sole risk. The service is provided on an "AS IS" and "AS AVAILABLE" basis without any warranty of any kind.',
    'legal.limitation-liability': 'Limitation of Liability',
    'legal.limitation-liability-text': 'In no event shall the platform, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages.',
    'legal.governing-law': 'Governing Law',
    'legal.governing-law-text': 'These Terms shall be governed and construed in accordance with the laws applicable in the jurisdiction where the platform is registered.',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.bots': 'Bots',
    'nav.add-bot': 'Bot hinzufügen',
    'nav.admin': 'Admin',
    'nav.profile': 'Profil',
    'nav.login': 'Anmelden',
    'nav.register': 'Registrieren',
    'nav.logout': 'Abmelden',
    'nav.search': 'Suchen',
    'nav.servers': 'Server',
    'nav.add-server': 'Server hinzufügen',
    'nav.account': 'Konto',
    
    // Home page
    'home.title': 'Entdecke Discord Bots',
    'home.subtitle': 'Finde den perfekten Bot für deinen Discord-Server',
    'home.search-placeholder': 'Suche nach Name, Kategorie oder Funktion',
    'home.explore': 'Bots erkunden',
    'home.popular': 'Beliebte Bots',
    'home.recent': 'Kürzlich hinzugefügt',
    'home.featured': 'Empfohlene Bots',
    
    // Auth
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.confirm-password': 'Passwort bestätigen',
    'auth.username': 'Benutzername',
    'auth.username-placeholder': 'Gib deinen Benutzernamen ein',
    'auth.forgot-password': 'Passwort vergessen?',
    'auth.already-account': 'Bereits ein Konto?',
    'auth.no-account': 'Noch kein Konto?',
    'auth.or': 'oder',
    'auth.login-with-google': 'Mit Google anmelden',
    'auth.register-with-google': 'Mit Google registrieren',
    'auth.login-with-discord': 'Mit Discord anmelden',
    'auth.register-with-discord': 'Mit Discord registrieren',
    'auth.login-description': 'Melde dich an, um deine Bots und Server zu verwalten',
    'auth.register-description': 'Erstelle ein Konto, um deine Bots und Server zu unserem Verzeichnis hinzuzufügen',
    
    // Bot details
    'bot.add': 'Bot hinzufügen',
    'bot.edit': 'Bot bearbeiten',
    'bot.delete': 'Bot löschen',
    'bot.name': 'Bot-Name',
    'bot.description': 'Beschreibung',
    'bot.id': 'Bot-ID',
    'bot.prefix': 'Präfix',
    'bot.category': 'Kategorie',
    'bot.website': 'Webseite',
    'bot.invite': 'Bot einladen',
    'bot.support': 'Support-Server',
    'bot.github': 'GitHub-Repository',
    'bot.tags': 'Tags',
    'bot.save': 'Bot speichern',
    'bot.cancel': 'Abbrechen',
    'bot.owner': 'Besitzer',
    'bot.created': 'Erstellt',
    'bot.updated': 'Aktualisiert',
    'bot.stars': 'Sterne',
    'bot.verified': 'Verifiziert',
    'bot.no-description': 'Keine Beschreibung vorhanden',
    'bot.unknown': 'Unbekannt',
    'bot.not-found': 'Bot nicht gefunden',
    'bot.not-found-description': 'Der gesuchte Bot existiert nicht oder wurde entfernt.',
    'bot.back-to-bots': 'Zurück zu Bots',
    'bot.view-details': 'Details anzeigen',
    'bot.directory': 'Bot-Verzeichnis',
    'bot.directory-desc': 'Durchsuche und entdecke Discord-Bots für deinen Server',
    'bot.none-found': 'Keine Bots gefunden',
    'bot.be-first': 'Sei der Erste, der einen Bot hinzufügt!',
    'bot.add-yours': 'Füge deinen Bot hinzu',
    'bot.last-updated': 'Zuletzt aktualisiert',
    'bot.bump': 'Hochstufen',
    'bot.bumping': 'Wird hochgestuft...',
    
    // Server
    'server.add': 'Server hinzufügen',
    'server.edit': 'Server bearbeiten',
    'server.delete': 'Server löschen',
    'server.name': 'Server-Name',
    'server.description': 'Beschreibung',
    'server.invite': 'Einladungslink',
    'server.members': 'Mitglieder',
    'server.join': 'Server beitreten',
    'server.tags': 'Tags',
    
    // Admin
    'admin.title': 'Admin-Panel',
    'admin.users': 'Benutzer',
    'admin.bots': 'Bots',
    'admin.reports': 'Berichte',
    'admin.settings': 'Einstellungen',
    'admin.pending': 'Ausstehende Bots',
    'admin.servers': 'Discord-Server',
    'admin.overview': 'Übersicht',
    'admin.user-management': 'Benutzerverwaltung',
    'admin.verified-bots': 'Verifizierte Bots',
    'admin.pending-bots': 'Ausstehende Verifizierung',
    'admin.server-management': 'Serververwaltung',
    'admin.total-users': 'Benutzer insgesamt',
    'admin.total-bots': 'Bots insgesamt',
    'admin.total-servers': 'Server insgesamt',
    'admin.pending-verification': 'Ausstehende Verifizierung',
    'admin.registered-users': 'Registrierte Benutzer',
    'admin.verification-required': 'Prüfung erforderlich',
    'admin.refresh': 'Aktualisieren',
    'admin.approve': 'Genehmigen',
    'admin.decline': 'Ablehnen',
    'admin.remove-admin': 'Admin-Rechte entfernen',
    'admin.make-admin': 'Zum Admin machen',
    'admin.last-updated': 'Zuletzt aktualisiert',
    'admin.user-details': 'Benutzerdetails',
    'admin.close': 'Schließen',
    'admin.error-fetching-bots': 'Fehler beim Abrufen der Bots',
    
    // Account manager
    'account.title': 'Kontoverwaltung',
    'account.profile': 'Profil',
    'account.settings': 'Einstellungen',
    'account.security': 'Sicherheit',
    'account.connected': 'Verbundene Konten',
    'account.theme': 'Design',
    'account.theme.light': 'Heller Modus',
    'account.theme.dark': 'Dunkler Modus',
    'account.theme.system': 'Systemeinstellung',
    'account.language': 'Sprache',
    'account.save': 'Änderungen speichern',
    'account.delete': 'Konto löschen',
    
    // Footer
    'footer.privacy': 'Datenschutz',
    'footer.imprint': 'Impressum',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.contact': 'Kontakt',
    'footer.language': 'Sprache',
    
    // Misc
    'misc.loading': 'Wird geladen...',
    'misc.error': 'Ein Fehler ist aufgetreten',
    'misc.success': 'Erfolg!',
    'misc.search': 'Suchen',
    'misc.save': 'Speichern',
    'misc.cancel': 'Abbrechen',
    'misc.delete': 'Löschen',
    'misc.edit': 'Bearbeiten',
    'misc.view': 'Ansehen',
    'misc.create': 'Erstellen',
    'misc.submit': 'Absenden',
    'misc.back': 'Zurück',
    'misc.next': 'Weiter',
    'misc.previous': 'Zurück',
    'misc.unknown': 'Unbekannt',
    'misc.back-to-bots': 'Zurück zu Bots',
    'misc.saving': 'Wird gespeichert...',
    
    // Cookie banner
    'cookie.title': 'Cookie-Hinweis',
    'cookie.description': 'Wir verwenden Cookies, um sicherzustellen, dass Sie die beste Erfahrung auf unserer Website haben.',
    'cookie.accept': 'Alle akzeptieren',
    'cookie.decline': 'Ablehnen',
    'cookie.preferences': 'Anpassen',
    
    // Profile
    'profile.title': 'Profil',
    'profile.edit': 'Profil bearbeiten',
    'profile.bots': 'Meine Bots',
    'profile.settings': 'Einstellungen',
    'profile.your-profile': 'Dein Profil',
    'profile.manage-details': 'Verwalte deine Profildetails',
    'profile.edit-profile': 'Profil bearbeiten',
    'profile.update-information': 'Aktualisiere deine Profilinformationen',
    'profile.username': 'Benutzername',
    'profile.username-placeholder': 'Gib deinen Benutzernamen ein',
    'profile.bio': 'Biografie',
    'profile.bio-placeholder': 'Erzähle uns etwas über dich',
    'profile.website': 'Webseite',
    'profile.website-placeholder': 'Deine Webseiten-URL',
    'profile.save-changes': 'Änderungen speichern',
    'profile.your-bots': 'Deine Bots',
    'profile.manage-bots': 'Verwalte deine Discord-Bots',
    'profile.view-bot': 'Bot anzeigen',
    
    // Legal
    'legal.imprint': 'Impressum',
    'legal.company-information': 'Unternehmensinformationen',
    'legal.company-name': 'Discord Bot Verzeichnis',
    'legal.company-address': 'Bot-Straße 123',
    'legal.company-city': 'Bot-Stadt, 10115',
    'legal.company-country': 'Botland',
    'legal.contact': 'Kontakt',
    'legal.email': 'E-Mail',
    'legal.phone': 'Telefon',
    'legal.registration': 'Registrierung',
    'legal.registration-text': 'Eingetragen im Handelsregister von Bot-Stadt. Registrierungsnummer: BOT123456',
    'legal.vat': 'Umsatzsteuer-ID',
    'legal.vat-text': 'Umsatzsteuer-Identifikationsnummer gemäß § 27a Umsatzsteuergesetz: DE123456789',
    'legal.responsible-content': 'Verantwortlich für den Inhalt',
    'legal.responsible-content-text': 'Verantwortlich für den Inhalt gemäß § 55 Abs. 2 RStV: Max Mustermann, Bot-Straße 123, Bot-Stadt, 10115 Botland',
    'legal.dispute-resolution': 'Streitbeilegung',
    'legal.dispute-resolution-text': 'Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: https://ec.europa.eu/consumers/odr. Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.',
    'legal.privacy-policy': 'Datenschutzerklärung',
    'legal.information-collection': 'Informationserfassung',
    'legal.information-collection-text': 'Wir sammeln Informationen, die Sie uns direkt bei der Registrierung eines Kontos, beim Hinzufügen von Bots oder bei der Interaktion mit unserer Plattform zur Verfügung stellen. Dazu gehören E-Mail-Adressen, Benutzernamen und Discord-IDs.',
    'legal.information-usage': 'Verwendung von Informationen',
    'legal.information-usage-text': 'Wir verwenden Informationen über Sie, um unsere Dienste bereitzustellen, zu warten und zu verbessern, neue Funktionen zu entwickeln und die Plattform und unsere Benutzer zu schützen.',
    'legal.information-protection': 'Informationsschutz',
    'legal.information-protection-text': 'Wir implementieren Maßnahmen, die darauf ausgelegt sind, die Sicherheit Ihrer persönlichen Daten zu gewährleisten. Allerdings ist keine Übertragungsmethode über das Internet zu 100% sicher.',
    'legal.cookie-usage': 'Cookie-Nutzung',
    'legal.cookie-usage-text': 'Wir verwenden Cookies und ähnliche Technologien, um Informationen darüber zu sammeln, wie Sie mit unseren Diensten interagieren, und um bestimmte Präferenzen zu speichern.',
    'legal.third-party-disclosure': 'Weitergabe an Dritte',
    'legal.third-party-disclosure-text': 'Wir verkaufen, handeln oder übertragen Ihre persönlich identifizierbaren Informationen nicht ohne Ihre Zustimmung an Dritte.',
    'legal.third-party-links': 'Links zu Drittanbietern',
    'legal.third-party-links-text': 'Unser Dienst kann Links zu Websites oder Diensten von Drittanbietern enthalten. Wir haben keine Kontrolle über und übernehmen keine Verantwortung für den Inhalt, die Datenschutzrichtlinien oder Praktiken von Websites oder Diensten Dritter.',
    'legal.gdpr-compliance': 'DSGVO-Konformität',
    'legal.gdpr-compliance-text': 'Für Benutzer in der Europäischen Union bieten wir Rechte bezüglich Ihrer personenbezogenen Daten, einschließlich des Rechts auf Zugriff, Korrektur oder Löschung Ihrer persönlichen Daten.',
    'legal.childrens-privacy': 'Datenschutz für Kinder',
    'legal.childrens-privacy-text': 'Unsere Dienste richten sich nicht an Personen unter 13 Jahren. Wir sammeln wissentlich keine persönlich identifizierbaren Informationen von Kindern unter 13 Jahren.',
    'legal.changes-to-policy': 'Änderungen an der Richtlinie',
    'legal.changes-to-policy-text': 'Wir können unsere Datenschutzrichtlinie von Zeit zu Zeit aktualisieren. Wir werden Sie über Änderungen informieren, indem wir die neue Datenschutzrichtlinie auf dieser Seite veröffentlichen.',
    'legal.contact-us': 'Kontaktieren Sie uns',
    'legal.contact-us-text': 'Wenn Sie Fragen zu dieser Datenschutzrichtlinie haben, kontaktieren Sie uns bitte über die Plattform oder über die angegebenen Kontaktinformationen.',
    'legal.terms-of-service': 'Nutzungsbedingungen',
    'legal.acceptance': 'Annahme der Bedingungen',
    'legal.terms-acceptance-text': 'Durch den Zugriff auf und die Nutzung dieses Discord Bot Verzeichnisses akzeptieren Sie und stimmen zu, an die Bedingungen und Bestimmungen dieser Vereinbarung gebunden zu sein.',
    'legal.eligibility': 'Teilnahmeberechtigung',
    'legal.eligibility-text': 'Um unsere Dienste nutzen zu können, müssen Sie mindestens 13 Jahre alt sein und den Nutzungsbedingungen von Discord entsprechen.',
    'legal.user-accounts': 'Benutzerkonten',
    'legal.user-accounts-text': 'Benutzer sind für die Aufrechterhaltung der Sicherheit ihres Kontos und Passworts verantwortlich. Die Plattform kann und wird nicht für Verluste oder Schäden haftbar gemacht werden, die aus Ihrer Nichterfüllung dieser Sicherheitsverpflichtung resultieren.',
    'legal.user-content': 'Benutzerinhalte',
    'legal.user-content-text': 'Sie sind verantwortlich für alle Inhalte und Aktivitäten, die unter Ihrem Konto stattfinden. Schädliche oder missbräuchliche Inhalte sind strengstens verboten.',
    'legal.prohibited-conduct': 'Verbotenes Verhalten',
    'legal.prohibited-conduct-text': 'Benutzer dürfen sich nicht an Aktivitäten beteiligen, die die Dienste oder Server der Plattform stören oder beeinträchtigen.',
    'legal.intellectual-property': 'Geistiges Eigentum',
    'legal.intellectual-property-text': 'Der Dienst und seine ursprünglichen Inhalte, Funktionen und Funktionalitäten sind Eigentum der Plattform und sind durch internationale Urheberrechts-, Marken-, Patent-, Geschäftsgeheimnis- und andere Gesetze zum geistigen Eigentum geschützt.',
    'legal.termination': 'Kündigung',
    'legal.termination-text': 'Wir können Ihr Konto kündigen oder sperren und den Zugang zum Dienst sofort, ohne vorherige Ankündigung oder Haftung, nach eigenem Ermessen, aus irgendeinem Grund und ohne Einschränkung verweigern.',
    'legal.disclaimer': 'Haftungsausschluss',
    'legal.disclaimer-text': 'Ihre Nutzung des Dienstes erfolgt auf eigenes Risiko. Der Dienst wird "WIE ER IST" und "WIE VERFÜGBAR" ohne jegliche Garantie angeboten.',
    'legal.limitation-liability': 'Haftungsbeschränkung',
    'legal.limitation-liability-text': 'In keinem Fall haften die Plattform, ihre Direktoren, Mitarbeiter, Partner, Agenten, Lieferanten oder verbundenen Unternehmen für indirekte, zufällige, besondere, Folge- oder Strafschäden.',
    'legal.governing-law': 'Geltendes Recht',
    'legal.governing-law-text': 'Diese Bedingungen unterliegen den Gesetzen der Jurisdiktion, in der die Plattform registriert ist, und werden in Übereinstimmung mit diesen ausgelegt.',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.bots': 'Bots',
    'nav.add-bot': 'Añadir Bot',
    'nav.admin': 'Admin',
    'nav.profile': 'Perfil',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar Sesión',
    'nav.search': 'Buscar',
    'nav.servers': 'Servidores',
    'nav.add-server': 'Añadir Servidor',
    'nav.account': 'Cuenta',
    
    // Home page
    'home.title': 'Descubre Bots de Discord',
    'home.subtitle': 'Encuentra el bot perfecto para tu servidor de Discord',
    'home.search-placeholder': 'Buscar por nombre, categoría o función',
    'home.explore': 'Explorar Bots',
    'home.popular': 'Bots Populares',
    'home.recent': 'Añadidos Recientemente',
    'home.featured': 'Bots Destacados',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirm-password': 'Confirmar Contraseña',
    'auth.username': 'Nombre de Usuario',
    'auth.username-placeholder': 'Introduce tu nombre de usuario',
    'auth.forgot-password': '¿Olvidaste tu contraseña?',
    'auth.already-account': '¿Ya tienes una cuenta?',
    'auth.no-account': '¿No tienes una cuenta?',
    'auth.or': 'o',
    'auth.login-with-google': 'Iniciar sesión con Google',
    'auth.register-with-google': 'Registrarse con Google',
    'auth.login-with-discord': 'Iniciar sesión con Discord',
    'auth.register-with-discord': 'Registrarse con Discord',
    'auth.login-description': 'Inicia sesión para gestionar tus bots y servidores',
    'auth.register-description': 'Crea una cuenta para añadir tus bots y servidores a nuestro directorio',
    
    // Bot details
    'bot.add': 'Añadir Bot',
    'bot.edit': 'Editar Bot',
    'bot.delete': 'Eliminar Bot',
    'bot.name': 'Nombre del Bot',
    'bot.description': 'Descripción',
    'bot.id': 'ID del Bot',
    'bot.prefix': 'Prefijo',
    'bot.category': 'Categoría',
    'bot.website': 'Sitio Web',
    'bot.invite': 'Invitar Bot',
    'bot.support': 'Servidor de Soporte',
    'bot.github': 'Repositorio GitHub',
    'bot.tags': 'Etiquetas',
    'bot.save': 'Guardar Bot',
    'bot.cancel': 'Cancelar',
    'bot.owner': 'Propietario',
    'bot.created': 'Creado',
    'bot.updated': 'Actualizado',
    'bot.stars': 'estrellas',
    'bot.verified': 'Verificado',
    'bot.no-description': 'Sin descripción',
    'bot.unknown': 'Desconocido',
    'bot.not-found': 'Bot no encontrado',
    'bot.not-found-description': 'El bot que buscas no existe o ha sido eliminado.',
    'bot.back-to-bots': 'Volver a los Bots',
    'bot.view-details': 'Ver Detalles',
    'bot.directory': 'Directorio de Bots',
    'bot.directory-desc': 'Explora y descubre bots de Discord para tu servidor',
    'bot.none-found': 'No se encontraron bots',
    'bot.be-first': '¡Sé el primero en añadir un bot!',
    'bot.add-yours': 'Añade tu Bot',
    'bot.last-updated': 'Última actualización',
    'bot.bump': 'Impulsar',
    'bot.bumping': 'Impulsando...',
    
    // Admin
    'admin.title': 'Panel de Administración',
    'admin.users': 'Usuarios',
    'admin.bots': 'Bots',
    'admin.reports': 'Reportes',
    'admin.settings': 'Configuración',
    'admin.pending': 'Bots Pendientes',
    'admin.servers': 'Servidores Discord',
    'admin.overview': 'Resumen',
    'admin.user-management': 'Gestión de Usuarios',
    'admin.verified-bots': 'Bots Verificados',
    'admin.pending-bots': 'Verificación Pendiente',
    'admin.server-management': 'Gestión de Servidores',
    'admin.total-users': 'Total de Usuarios',
    'admin.total-bots': 'Total de Bots',
    'admin.total-servers': 'Total de Servidores',
    'admin.pending-verification': 'Verificación Pendiente',
    'admin.registered-users': 'Usuarios Registrados',
    'admin.verification-required': 'Verificación Requerida',
    'admin.refresh': 'Actualizar',
    'admin.approve': 'Aprobar',
    'admin.decline': 'Rechazar',
    'admin.remove-admin': 'Quitar Derechos de Admin',
    'admin.make-admin': 'Hacer Admin',
    'admin.last-updated': 'Última actualización',
    'admin.user-details': 'Detalles del Usuario',
    'admin.close': 'Cerrar',
    'admin.error-fetching-bots': 'Error al obtener los bots',
    
    // Footer
    'footer.privacy': 'Política de Privacidad',
    'footer.imprint': 'Aviso Legal',
    'footer.terms': 'Términos de Servicio',
    'footer.contact': 'Contacto',
    'footer.language': 'Idioma',
    
    // Misc
    'misc.loading': 'Cargando...',
    'misc.error': 'Ha ocurrido un error',
    'misc.success': '¡Éxito!',
    'misc.search': 'Buscar',
    'misc.save': 'Guardar',
    'misc.cancel': 'Cancelar',
    'misc.delete': 'Eliminar',
    'misc.edit': 'Editar',
    'misc.view': 'Ver',
    'misc.create': 'Crear',
    'misc.submit': 'Enviar',
    'misc.back': 'Atrás',
    'misc.next': 'Siguiente',
    'misc.previous': 'Anterior',
    'misc.unknown': 'Desconocido',
    'misc.back-to-bots': 'Volver a los Bots',
    'misc.saving': 'Guardando...',
    
    // Cookie banner
    'cookie.title': 'Aviso de Cookies',
    'cookie.description': 'Utilizamos cookies para garantizar que obtenga la mejor experiencia en nuestro sitio web.',
    'cookie.accept': 'Aceptar Todo',
    'cookie.decline': 'Rechazar',
    'cookie.preferences': 'Personalizar',
    
    // Profile
    'profile.title': 'Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.bots': 'Mis Bots',
    'profile.settings': 'Configuración',
    'profile.your-profile': 'Tu Perfil',
    'profile.manage-details': 'Gestiona los detalles de tu perfil',
    'profile.edit-profile': 'Editar Perfil',
    'profile.update-information': 'Actualizar información de perfil',
    'profile.username': 'Nombre de usuario',
    'profile.username-placeholder': 'Introduce tu nombre de usuario',
    'profile.bio': 'Biografía',
    'profile.bio-placeholder': 'Cuéntanos sobre ti',
    'profile.website': 'Sitio web',
    'profile.website-placeholder': 'URL de tu sitio web',
    'profile.save-changes': 'Guardar Cambios',
    'profile.your-bots': 'Tus Bots',
    'profile.manage-bots': 'Gestiona tus bots de Discord',
    'profile.view-bot': 'Ver Bot',
    
    // Legal
    'legal.imprint': 'Aviso Legal',
    'legal.company-information': 'Información de la Empresa',
    'legal.company-name': 'Directorio de Bots de Discord',
    'legal.company-address': 'Calle Bot 123',
    'legal.company-city': 'Ciudad Bot, 10115',
    'legal.company-country': 'Botland',
    'legal.contact': 'Contacto',
    'legal.email': 'Correo Electrónico',
    'legal.phone': 'Teléfono',
    'legal.registration': 'Registro',
    'legal.registration-text': 'Registrado en el Registro Mercantil de Ciudad Bot. Número de registro: BOT123456',
    'legal.vat': 'IVA',
    'legal.vat-text': 'Número de Identificación de IVA según § 27a de la Ley del Impuesto sobre el Valor Añadido: DE123456789',
    'legal.responsible-content': 'Responsable del Contenido',
    'legal.responsible-content-text': 'Persona responsable del contenido de acuerdo con § 55 Abs. 2 RStV: Juan Pérez, Calle Bot 123, Ciudad Bot, 10115 Botland',
    'legal.dispute-resolution': 'Resolución de Disputas',
    'legal.dispute-resolution-text': 'La Comisión Europea proporciona una plataforma para la resolución de disputas en línea (OS): https://ec.europa.eu/consumers/odr. No estamos dispuestos ni obligados a participar en procedimientos de resolución de disputas ante una junta de arbitraje de consumidores.',
    'legal.privacy-policy': 'Política de Privacidad',
    'legal.information-collection': 'Recopilación de Información',
    'legal.information-collection-text': 'Recopilamos información que nos proporciona directamente al registrar una cuenta, agregar bots o interactuar con nuestra plataforma. Esto incluye direcciones de correo electrónico, nombres de usuario e IDs de Discord.',
    'legal.information-usage': 'Uso de la Información',
    'legal.information-usage-text': 'Utilizamos información sobre usted para proporcionar, mantener y mejorar nuestros servicios, desarrollar nuevas funciones y proteger la plataforma y nuestros usuarios.',
    'legal.information-protection': 'Protección de la Información',
    'legal.information-protection-text': 'Implementamos medidas diseñadas para garantizar la seguridad de su información personal. Sin embargo, ningún método de transmisión por Internet es 100% seguro.',
    'legal.cookie-usage': 'Uso de Cookies',
    'legal.cookie-usage-text': 'Utilizamos cookies y tecnologías similares para recopilar información sobre cómo interactúa con nuestros servicios y para recordar ciertas preferencias.',
    'legal.third-party-disclosure': 'Divulgación a Terceros',
    'legal.third-party-disclosure-text': 'No vendemos, intercambiamos ni transferimos su información personalmente identificable a terceros sin su consentimiento.',
    'legal.third-party-links': 'Enlaces a Terceros',
    'legal.third-party-links-text': 'Nuestro servicio puede contener enlaces a sitios web o servicios de terceros. No tenemos control ni asumimos responsabilidad por el contenido, las políticas de privacidad o las prácticas de sitios web o servicios de terceros.',
    'legal.gdpr-compliance': 'Cumplimiento del RGPD',
    'legal.gdpr-compliance-text': 'Para los usuarios de la Unión Europea, proporcionamos derechos sobre sus datos personales, incluido el derecho a acceder, corregir o eliminar su información personal.',
    'legal.childrens-privacy': 'Privacidad de los Niños',
    'legal.childrens-privacy-text': 'Nuestros servicios no están dirigidos a personas menores de 13 años. No recopilamos a sabiendas información personalmente identificable de niños menores de 13 años.',
    'legal.changes-to-policy': 'Cambios en la Política',
    'legal.changes-to-policy-text': 'Podemos actualizar nuestra Política de Privacidad de vez en cuando. Le notificaremos cualquier cambio publicando la nueva Política de Privacidad en esta página.',
    'legal.contact-us': 'Contáctenos',
    'legal.contact-us-text': 'Si tiene alguna pregunta sobre esta Política de Privacidad, contáctenos a través de la plataforma o mediante la información de contacto proporcionada.',
    'legal.terms-of-service': 'Términos de Servicio',
    'legal.acceptance': 'Aceptación de Términos',
    'legal.terms-acceptance-text': 'Al acceder y utilizar este Directorio de Bots de Discord, acepta y acuerda estar sujeto a los términos y disposiciones de este acuerdo.',
    'legal.eligibility': 'Elegibilidad',
    'legal.eligibility-text': 'Para utilizar nuestros servicios, debe tener al menos 13 años de edad y cumplir con los Términos de Servicio de Discord.',
    'legal.user-accounts': 'Cuentas de Usuario',
    'legal.user-accounts-text': 'Los usuarios son responsables de mantener la seguridad de su cuenta y contraseña. La plataforma no puede y no será responsable por cualquier pérdida o daño derivado de su incumplimiento de esta obligación de seguridad.',
    'legal.user-content': 'Contenido del Usuario',
    'legal.user-content-text': 'Usted es responsable de todo el contenido y actividad que ocurre bajo su cuenta. El contenido dañino o abusivo está estrictamente prohibido.',
    'legal.prohibited-conduct': 'Conducta Prohibida',
    'legal.prohibited-conduct-text': 'Los usuarios no pueden participar en ninguna actividad que interfiera o interrumpa los servicios o servidores conectados a la plataforma.',
    'legal.intellectual-property': 'Propiedad Intelectual',
    'legal.intellectual-property-text': 'El servicio y su contenido, características y funcionalidad originales son propiedad de la plataforma y están protegidos por derechos de autor internacionales, marcas registradas, patentes, secretos comerciales y otras leyes de propiedad intelectual.',
    'legal.termination': 'Terminación',
    'legal.termination-text': 'Podemos terminar o suspender su cuenta y prohibir el acceso al servicio inmediatamente, sin previo aviso o responsabilidad, bajo nuestra única discreción, por cualquier motivo y sin limitación.',
    'legal.disclaimer': 'Exención de Responsabilidad',
    'legal.disclaimer-text': 'Su uso del servicio es bajo su propio riesgo. El servicio se proporciona "TAL CUAL" y "SEGÚN DISPONIBILIDAD" sin garantía de ningún tipo.',
    'legal.limitation-liability': 'Limitación de Responsabilidad',
    'legal.limitation-liability-text': 'En ningún caso la plataforma, ni sus directores, empleados, socios, agentes, proveedores o afiliados, serán responsables por daños indirectos, incidentales, especiales, consecuentes o punitivos.',
    'legal.governing-law': 'Ley Aplicable',
    'legal.governing-law-text': 'Estos Términos se regirán e interpretarán de acuerdo con las leyes aplicables en la jurisdicción donde está registrada la plataforma.',
  }
};

// Language provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Get browser language or use English as default
  const getBrowserLanguage = (): Language => {
    const browserLang = navigator.language.split('-')[0];
    return (browserLang === 'de' || browserLang === 'es') ? browserLang as Language : 'en';
  };

  // Get stored language or browser language
  const getInitialLanguage = (): Language => {
    const storedLanguage = localStorage.getItem('language') as Language;
    return storedLanguage || getBrowserLanguage();
  };

  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  // Set language and save to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  // Translate a key
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  // Set document language on initial load
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
